services:
  airflow-scheduler:
    volumes: ["./data:/opt/airflow/data"]
  airflow-apiserver:
    volumes: ["./data:/opt/airflow/data"]
    ports: !override
      - "8081:8080"
  airflow-worker:
    volumes: ["./data:/opt/airflow/data"]
  airflow-triggerer:
    volumes: ["./data:/opt/airflow/data"]
  airflow-init:
    volumes: ["./data:/opt/airflow/data"]
